import "../../globals.css";
export const metadata = {
  title: "Admin Login | Kishorgonj Keshba Fazil Madrasha",
  description: "Generated by Md abdur rahman sifat",
};

export default function LoginLayout({ children }) {
  return <section className="">{children}</section>;
}
