import "../globals.css";

interface LoginLayoutProps {
    children: React.ReactNode;
}

export const metadata = {
    title: "Admin Login | Kishorgonj Keshba Fazil Madrasha",
    description: "Generated by Md abdur rahman sifat",
};

export default function LoginLayout({ children }: LoginLayoutProps) {
    return <section className="">{children}</section>;
}
